name = "HackYourHeart"
license = "MIT"
licenselink = "https://github.com/TajangSec/HackYourHeart/blob/main/LICENSE"
description = "Hack your heart OvO! A HackTheBox-style theme."

# The home page of the theme, where the source can be found
homepage = "https://github.com/TajangSec/HackYourHeart"

# If you have a running demo of the theme
demosite = "https://demo.h4cker.zip/"

# Taxonomy terms
tags = [
  "blog",
  "hacker",
  "technology",
  "dark",
  "geek",
  "card",
  "ctf"
]
features = [
  "i18n",
  "Hacker",
  "Technology",
  "Geek",
  "Card",
  "SEO Optimized",
  "friends link template",
  "syntax-highlighting",
  "cover-image",
  "favicon",
  "social links"
]


# If the theme has a single author
[author]
name = "Tajang"
homepage = "https://h4cker.zip/"
